#! /usr/bin/env ruby

# Copyright 2016 Ladislav Slezak
# This is apk2zip version 0.1

require "zlib"
require "zip"
require "stringio"

class ApkReader
  def initialize(apk)

    io = Zlib::GzipReader.new(StringIO.new(apk))

    # read the header - the route name
    self.route = read_header(io)
    # TODO: any idea why is it here 3 times?
    read_header(io)
    read_header(io)

    # TODO: here are 8 bytes, the meaning is unclear...
    read_int(io)
    read_int(io)

    self.content = {}

    until io.eof?
      file, val = read_file(io)
      content[file] = val
    end
  end

  attr_reader :content, :route

private

  attr_writer :content, :route

  def read_int(io)
    data = io.read(4)
    data.unpack("V").first
  end

  def read_header(io)
    len = read_int(io)

    data = io.read((len - 1)*2).force_encoding("UTF-16LE").encode("UTF-8")
    # NULL terminator
    io.read(2)

    data
  end

  def read_file(io)
    file_len = read_int(io)
    name_len = read_int(io)
    
    name = io.read((name_len - 1)*2).force_encoding("UTF-16LE").encode("UTF-8")
    # NULL terminator
    io.read(2)

    # change file separator if needed
    if File::SEPARATOR != "\\"
      name.gsub!("\\", File::SEPARATOR)
    end
    
    data = io.read(file_len).force_encoding("UTF-16LE")
    [name, data]
  end
end

class ZipMaker
  def initialize(content)
    self.files = content
  end

  def build
    stringio = Zip::OutputStream.write_buffer do |zio|
      files.each do |name, value|
        zio.put_next_entry(name)
        zio.write(value)
      end
    end
    stringio.string
  end
  
private
  
  attr_accessor :files
end

#######################################################################

filename = ARGV[0]

if filename.nil? || filename.empty?
  puts "Usage: #{__FILE__} <apk_file>"
  exit 1
end

puts "Reading APK file #{filename}..."
apk = ApkReader.new(File.read(filename))
puts "The activity is for route '#{apk.route}'"
puts "Found #{apk.content.size} files inside"

Zip.default_compression = Zlib::BEST_COMPRESSION

zip = ZipMaker.new(apk.content)

if filename.end_with?(".apk") || filename.end_with?(".APK")
  newfile = filename[0..-4] + "zip"
else
  newfile = filename + ".zip"
end

puts "Creating ZIP file..."
File.write(newfile, zip.build)
puts "Saved to #{newfile}"
